Add Optimal Path to Score Feature
brandonabela/8-Ball-Pool-Bot pull request #9
Opened 2019-12-06 19:10 UTC by brandonabela

2020-02-15 17:57 UTC, KeithGeorgeCiantar requested changes
Some minor changes requested, otherwise everything seems to be ok.

2020-02-15 17:57 UTC, KeithGeorgeCiantar commented on Logic/dijkstra_graph.py
> +
Maybe add a small comment that Dijkstra is used to get the nodes in the shortest path

2020-02-15 17:57 UTC, KeithGeorgeCiantar commented on Logic/ball_path.py
> +        l_b = line_terms[1]
Do a and b refer to x and y or are they like 'ax + by + c = 0'?

2020-02-15 17:57 UTC, KeithGeorgeCiantar commented on Logic/ball_path.py
> +        return distance >= circle_radius
Does this take into consideration cases like the attached?

![Example](https://user-images.githubusercontent.com/52758149/74591562-33b31400-5019-11ea-8ff0-f28e6c1fe16e.png)

Also should it return true if it intercepts or false if it intercepts? Currently it returns false if it intercepts.

2020-02-15 17:57 UTC, KeithGeorgeCiantar commented on Logic/ball_path.py
> +        target_indexes = self.get_balls_index(balls, ball_colour)
Indices or Indexes? I am not sure and I have found this https://stackoverflow.com/questions/1378781/proper-terminology-should-i-say-indexes-or-indices which has some conflicting arguments. I think it's mainly important to choose one standard and use it throughout.

2020-02-15 17:57 UTC, KeithGeorgeCiantar commented on Logic/ball_path.py
> +        '''Determine if path is ocluded by other balls'''
Should be 'occluded' not 'ocluded'.

2020-02-15 17:57 UTC, KeithGeorgeCiantar commented on Logic/ball_path.py
> +                if not self.line_intercept_circle(line, a_ball, lookup.BALL_DIAMETER):
If the method takes radius, why are you using diameter?

2020-02-20 14:42 UTC, brandonabela commented on Logic/dijkstra_graph.py
> +
Done

2020-02-20 14:42 UTC, brandonabela commented on Logic/ball_path.py
> +        l_b = line_terms[1]
Done

2020-02-20 14:42 UTC, brandonabela commented on Logic/ball_path.py
> +        return distance >= circle_radius
Done

2020-02-20 14:42 UTC, brandonabela commented on Logic/ball_path.py
> +        target_indexes = self.get_balls_index(balls, ball_colour)
Done

2020-02-20 14:42 UTC, brandonabela commented on Logic/ball_path.py
> +        '''Determine if path is ocluded by other balls'''
Done

2020-02-20 14:42 UTC, brandonabela commented on Logic/ball_path.py
> +                if not self.line_intercept_circle(line, a_ball, lookup.BALL_DIAMETER):
Done

2020-02-20 14:43 UTC, KeithGeorgeCiantar approved these changes
Worked together on the new version. The new changes seems to work well.

2020-02-20 14:43 UTC, merged